[package]
name = "external"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde = "1.0.152"
zmq = "0.10.0"

